### ISSUE TITLE
Web page is dropping sample with same participant ID

### ISSUE THREAD

**Issue by illusional** [populationgenomics/sample-metadata#280]
See validation project for participant ID: `HG001_NA12878`. Mismatched `total_samples` and the earlier sample is missing.

Both samples exist in database, but for some reason only the latter is being inserted. Perhaps it's disjointed sample IDs, ie: one sample is inserted for participant A, then one for participant B, then another one for participant A (this doesn't happen often with the cohort I think).

**Comment by danielreti** [comment]
Fixed by #344
