### ISSUE TITLE
Create New Sequence Fails | Project Missing 

### ISSUE THREAD

**Issue by vivbak** [populationgenomics/sample-metadata#321]
Calling something like this 
`new_sequence = NewSequence(**sequence_info)
        seqapi.create_new_sequence(new_sequence=new_sequence)`
Results in  
`Exception has occurred: IntegrityError (note: full exception trace is shown but execution is paused at: create_sequence) (1048, "Column 'project' cannot be null")`

**Comment by vivbak** [comment]
@illusional, not sure the preferred behaviour here. It looks like it's currently the connection is `get_projectless_db_connection`. Should we just switch this to a ` get_project_write_connection`?

**Comment by illusional** [comment]
Do you have a full stack-trace?
