### ISSUE TITLE
Add links to multiQC reports

### ISSUE THREAD

**Issue by cassimons** [populationgenomics/sample-metadata#335]
The current seqr pipeline generates a number of project-level QC reports that must be visually inspected during processing. These reports are not versioned such that the latest version of the report is accessible at a stable URL in the project web bucket.  Currently, there is no way to navigate to a given report from a given project, rather you must construct the URL you wish to view (which gets old fast).

It would be super convenient if we could add a section to the[ project page](https://sample-metadata.populationgenomics.org.au/project/acute-care) that contains links to each of the relevant qc report types. The specific reports I had in mind currently are:
- [WGS Cram MultiQC](https://main-web.populationgenomics.org.au/acute-care/qc/cram/multiqc.html): `https://main-web.populationgenomics.org.au/{DATASET}/qc/cram/multiqc.html`  
- [WGS GVCF MultiQC](https://main-web.populationgenomics.org.au/acute-care/qc/gvcf/multiqc.html): `https://main-web.populationgenomics.org.au/{DATASET}/qc/gvcf/multiqc.html`
- [WGS FASTQC MultiQC](https://main-web.populationgenomics.org.au/acute-care/qc/fastqc/multiqc.html): `https://main-web.populationgenomics.org.au/{DATASET}/qc/fastqc/multiqc.html`
-  [Exome Cram MultiQC](https://main-web.populationgenomics.org.au/acute-care/exome/qc/cram/multiqc.html): `https://main-web.populationgenomics.org.au/{DATASET}/exome/qc/cram/multiqc.html`  
- [Exome GVCF MultiQC](https://main-web.populationgenomics.org.au/acute-care/exome/qc/gvcf/multiqc.html): `https://main-web.populationgenomics.org.au/{DATASET}/exome/qc/gvcf/multiqc.html`
- [Exome FASTQC MultiQC](https://main-web.populationgenomics.org.au/acute-care/exome/qc/fastqc/multiqc.html): `https://main-web.populationgenomics.org.au/{DATASET}/exome/qc/fastqc/multiqc.html`

Some reports may not exist for some projects either because:
- they have not been run yet
- they do not have both exome and genome data types
- some reports (fastqc) are not run by default 
We could muck around and only show links for reports that exist, however, I assume that would be non-trivial to establish so I would rather a fast interim solution that presents the URLs for all reports for all (RD) projects.

The links could be added into the current summary stats table at the top of the page or given their own section.

While we are adding useful links - adding a link to the relevant seqr project page would also be an awesome addition.

**Comment by danielreti** [comment]
@cassimons Looking into this now. 
As you say, I will not validate that the linked report exists, but will just naively list all potentially available reports. 
Assuming a link to seqr is similarly formulaic in the URL, what is the general URL format for that one? I can add it too :)

**Comment by danielreti** [comment]
Also thanks for making this issue! In future, could you please also either assign me to the issue (if it's not something deeply backend related), or post on Slack telling me you've created an issue. I wasn't notified that you'd created this and just happened to stumble across it while looking for something else - thanks!

**Comment by danielreti** [comment]
![Screenshot 2022-11-17 at 5 19 54 pm](https://user-images.githubusercontent.com/47542969/202371420-73becb94-f965-44d7-8412-72eeefe0e2e1.png)

**Comment by cassimons** [comment]
Thanks @danielreti , that looks great!
