### ISSUE TITLE
Update sample status isn't valid with new data model

### ISSUE THREAD

**Issue by illusional** [populationgenomics/sample-metadata#4]
Currently the [update sample status script](https://github.com/populationgenomics/sample-metadata/blob/main/update_sample_status/main.py):

- updates a field called "Sample status" where the sample ID (soon to be external ID) is some value

However, in our new model, a sample can have multiple pieces of sequencing, so this would actually refer to the status of some sequence that belongs to a sample. Specifically for TOB there is SS and WGS data, however the airtable manifest only represents the WGS that we're managing.

The work-around might be to add a method to the sample-metadata api called:

- `update_sample_sequence_by_type`, which takes a sample ID and the type of sequencing, and then we could just update the "last" sequencing with that type, because potentially if a sample fails QC, we'll re-sequence with the same sampleID.

**Comment by illusional** [comment]
A potential solution to this problem is addressed in 462b5cc, highlighting this query:

```sql
SELECT sq.id FROM sample_sequencing sq
INNER JOIN sample_sequencing_status sqs ON sq.id = sqs.sample_sequencing_id
WHERE sq.sample_id = {internal_sample_id}
ORDER BY sqs.timestamp DESC
LIMIT 1;
```

**Comment by illusional** [comment]
@vivbak, this issue can be closed now right?

**Comment by vivbak** [comment]
Oh yup, 
handled here https://github.com/populationgenomics/sample-metadata/pull/227 and here https://github.com/populationgenomics/sample-metadata/pull/247
