### ISSUE TITLE
Add regular DB backups

### ISSUE THREAD

**Issue by lgruen** [populationgenomics/sample-metadata#5]
- We should have something like a Cron job to regularly store a full DB backup to GCS (e.g. once a day).
- We should also have monitoring to alert us in case the backups don't happen.
- Once a year we should try disaster recovery by completely restoring the DB to a new instance.

**Comment by illusional** [comment]
@vivbak, how's your documentation for this going?

**Comment by vivbak** [comment]
Aloha, nearly ready for review :) 
https://github.com/populationgenomics/sample-metadata/pull/6

**Comment by lgruen** [comment]
Now that we're relying on the metadata server for seqr (yay!), we should make sure that the backups are working as soon as possible.

**Comment by vivbak** [comment]
Hi @lgruen :) As an update, most of this is done. You can find the update script here #9. 
I'll prioritize the DR documentation this week.

**Comment by lgruen** [comment]
Excellent, thanks!!

**Comment by illusional** [comment]
Hey @vivbak, I think this task has been actioned, are we right to close the issue?

**Comment by vivbak** [comment]
oh, yup :) Addressed in #28
